Repository TinkoffCreditSystems/zeppelin, pull requests merged in 2018-11, with the labels that each got.

#5 [DW-17913] display all column with the same name in ui-grid
  zeppelin-web/src/app/tabledata/tabledata.js
  zeppelin-web/src/app/visualization/builtins/visualization-table.js
Labels: tcs only, waiting apache

#4 [ZP-9] Add support for variables in JDBCInterpreter statementPrecode.
  jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
Labels: tcs only, tcs private

#6 [ZP-24] multiple paragraphs actions
  zeppelin-web/src/app/notebook/notebook-actionBar.html
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/app/notebook/notebook.css
  zeppelin-web/src/app/notebook/notebook.html
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/app/notebook/paragraph/paragraph.css
  zeppelin-web/src/app/notebook/paragraph/paragraph.html
  zeppelin-web/src/app/notebook/shortcut.html
Labels: tcs only, waiting apache

#11 [ZP-26] - Remove event if dom's element destroy
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/app/notebook/paragraph/resizable.directive.js
  zeppelin-web/src/app/notebook/paragraph/result/result.controller.js
Labels: tcs only, waiting apache

#7 [ZP-13] By default create new note in "Users/user_name/"
  zeppelin-integration/src/test/java/org/apache/zeppelin/AbstractZeppelinIT.java
  zeppelin-web/src/components/note-create/note-create.controller.js
Labels: tcs only, tcs private

#13 [ZP-20] Add 'Copy Column Name' to table visualisation-table
  zeppelin-web/src/app/visualization/builtins/visualization-table.js
Labels: tcs only, tcs private

#10 [ZP-36] Close interpreters in multithreaded mode
  zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSetting.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSettingManager.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/ManagedInterpreterGroup.java
Labels: Tinkoff only
