Repository TinkoffCreditSystems/zeppelin, pull requests merged in 2019-02, with the labels that each got.

#16 [ZP-62] [ZEPPELIN-3814] Add apply button to table settings
  zeppelin-web/src/app/visualization/builtins/visualization-table-setting.html
  zeppelin-web/src/app/visualization/builtins/visualization-table.js
Labels: Apache merged, PR for release 0.9

#41 [ZP-44] run selected code
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
  zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
  zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
  zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/components/websocket/websocket-message.service.js
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Paragraph.java
Labels: PR for release 0.9

#38 [ZP-42] - add favorites notes
  .gitignore
  pom.xml
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/FavoriteNotesRestApi.java
  zeppelin-web/src/app/home/home.controller.js
  zeppelin-web/src/app/home/home.css
  zeppelin-web/src/app/home/home.html
  zeppelin-web/src/app/notebook/notebook-actionBar.html
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/app/notebook/notebook.controller.test.js
  zeppelin-web/src/components/favorite-notes/favorite-notes.service.js
  zeppelin-web/src/components/note-action/note-action.service.js
  zeppelin-web/src/index.js
Labels: PR for release 0.9

#32 [ZP-103] Refactor `ConnectionManager` to avoid dead-lock
  zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
  zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
  zeppelin-server/src/test/java/org/apache/zeppelin/socket/NotebookServerTest.java
Labels: Apache PR, PR for release 0.9

#44 [ZP-57] UI: Исправить отображение имени ноутбука при наведении курсора
  zeppelin-web/src/app/notebook/notebook.css
Labels: PR for release 0.9

#45 [ZP-60] Minor refactoring of notebook dir traversal in VFSNotebookRepo
  zeppelin-plugins/notebookrepo/vfs/src/main/java/org/apache/zeppelin/notebook/repo/VFSNotebookRepo.java
Labels: PR for release 0.9

#46 [ZP-113 & ZP-118] Доработка автодополнения для tjdbc
  .travis.yml
  alluxio/src/main/java/org/apache/zeppelin/alluxio/AlluxioInterpreter.java
  alluxio/src/test/java/org/apache/zeppelin/alluxio/AlluxioInterpreterTest.java
  elasticsearch/src/main/java/org/apache/zeppelin/elasticsearch/ElasticsearchInterpreter.java
  elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/ElasticsearchInterpreterTest.java
  file/src/main/java/org/apache/zeppelin/file/HDFSFileInterpreter.java
  file/src/test/java/org/apache/zeppelin/file/HDFSFileInterpreterTest.java
  flink/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
  jdbc/src/main/java/org/apache/zeppelin/jdbc/SqlCompleter.java
  jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
  jdbc/src/test/java/org/apache/zeppelin/jdbc/SqlCompleterTest.java
  livy/src/main/java/org/apache/zeppelin/livy/BaseLivyInterpreter.java
  python/src/main/java/org/apache/zeppelin/python/IPythonInterpreter.java
  python/src/main/java/org/apache/zeppelin/python/PythonInterpreter.java
  sap/src/main/java/org/apache/zeppelin/sap/universe/UniverseCompleter.java
  spark/interpreter/src/main/java/org/apache/zeppelin/spark/DepInterpreter.java
  spark/interpreter/src/main/java/org/apache/zeppelin/spark/OldSparkInterpreter.java
  spark/interpreter/src/test/java/org/apache/zeppelin/spark/IPySparkInterpreterTest.java
  spark/spark-scala-parent/src/main/scala/org/apache/zeppelin/spark/BaseSparkScalaInterpreter.scala
  tjdbc/pom.xml
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/JDBCInterpreter.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/JDBCUserConfigurations.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/SqlCompleter.java
  tjdbc/src/main/resources/ansi.sql.keywords
  tjdbc/src/main/resources/postgresql-native-driver-sql.keywords
  tjdbc/src/test/java/ru/tinkoff/zeppelin/jdbc/JDBCInterpreterTest.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/AngularObjectId.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/AppOutputAppendEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/AppOutputUpdateEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/AppStatusUpdateEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/InterpreterCompletion.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/OutputAppendEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/OutputUpdateAllEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/OutputUpdateEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RegisterInfo.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteApplicationResult.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterContext.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterEvent.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterEventService.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterResult.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterResultMessage.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RemoteInterpreterService.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/thrift/RunParagraphsEvent.java
  zeppelin-interpreter/src/main/thrift/RemoteInterpreterService.thrift
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/app/notebook/paragraph/paragraph.css
  zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/JdbcIntegrationTest.java
Labels: PR for release 0.9

#49 Remove ConfigStorage
  zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSettingManager.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NotebookAuthorization.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/storage/ConfigStorage.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/storage/FileSystemConfigStorage.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/storage/LocalConfigStorage.java
  zeppelin-zengine/src/test/java/org/apache/zeppelin/conf/ZeppelinConfigurationTest.java
Labels: For Spring Rebase
