Repository TinkoffCreditSystems/zeppelin, pull requests merged in 2019-01, with the labels that each got.

#36 [ZP-54] - add stop running note functionality
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
  zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
  zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java
  zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java
  zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
  zeppelin-web/src/app/notebook/notebook-actionBar.html
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/components/websocket/websocket-message.service.js
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/socket/Message.java
  zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
Labels: PR for release 0.9

#34 [ZP-43] - add cron UI
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
  zeppelin-web/Gruntfile.js
  zeppelin-web/src/app/notebook/cron/cron.controller.js
  zeppelin-web/src/app/notebook/cron/cron.css
  zeppelin-web/src/app/notebook/cron/cron.html
  zeppelin-web/src/app/notebook/notebook-actionBar.html
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/app/notebook/notebook.controller.test.js
  zeppelin-web/src/index.html
  zeppelin-web/src/index.js
Labels: PR for release 0.9

#35 [ZP-12] - add zeppelin sql code beautifier
  zeppelin-web/package.json
  zeppelin-web/src/app/notebook/paragraph/paragraph-control.html
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/app/notebook/shortcut.html
Labels: PR for release 0.9

#37 [ZP-45] - bugfix: don't have permission window
  zeppelin-web/src/app/notebook/notebook.controller.js
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
  zeppelin-web/src/app/notebook/paragraph/result/result.controller.js
Labels: PR for release 0.9

#39 [ZP-83] Изолированно перенести наработки по автокомплиту
  conf/interpreter-list
  pom.xml
  tjdbc/pom.xml
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/JDBCInterpreter.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/JDBCUserConfigurations.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/SqlCompleter.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/SqlStatement.java
  tjdbc/src/main/java/ru/tinkoff/zeppelin/jdbc/security/JDBCSecurityImpl.java
  tjdbc/src/main/resources/ansi.sql.keywords
  tjdbc/src/main/resources/interpreter-setting.json
  tjdbc/src/main/resources/postgresql-native-driver-sql.keywords
  tjdbc/src/test/java/ru/tinkoff/zeppelin/jdbc/JDBCInterpreterInterpolationTest.java
  tjdbc/src/test/java/ru/tinkoff/zeppelin/jdbc/JDBCInterpreterTest.java
  tjdbc/src/test/java/ru/tinkoff/zeppelin/jdbc/SqlCompleterTest.java
  tjdbc/src/test/java/ru/tinkoff/zeppelin/jdbc/SqlStatementTest.java
  zeppelin-interpreter/src/main/java/org/apache/zeppelin/completer/CachedCompleter.java
  zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
Labels: PR for release 0.9, Tinkoff private

#20 [ZP-64] Add Quartz dynamic thread pool & REST API functionality for quartz configuration
  docs/usage/other_features/cron_scheduler.md
  docs/usage/rest_api/admin.md
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/AdminRestApi.java
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/exception/SchedulerConfigRuntimeException.java
  zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/SchedulerConfigRequest.java
  zeppelin-server/src/main/java/org/apache/zeppelin/service/AdminService.java
  zeppelin-server/src/test/java/org/apache/zeppelin/rest/AdminRestApiTest.java
  zeppelin-server/src/test/java/org/apache/zeppelin/service/AdminServiceTest.java
  zeppelin-server/src/test/resources/quartz.properties
  zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
  zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPool.java
  zeppelin-zengine/src/test/java/org/apache/zeppelin/scheduler/pool/DynamicThreadPoolTest.java
Labels: Apache PR, PR for release 0.9
